# -*- mode: ruby -*-
# vi: set ft=ruby:shiftwidth=2: tabstop=2: softtabstop=2 :

hosts = {
  "destroystack1" => "192.168.33.11",
  "destroystack2" => "192.168.33.22",
  "destroystack3" => "192.168.33.33"
}

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "fedora-18"
      #machine.vm.box_url = "http://static.stasiak.at/fedora-18-x86-2.box"
      #machine.vm.hostname = name
      machine.vm.network "private_network", ip: ip
      machine.vm.provision "shell",
        inline: "echo '123456'| passwd root --stdin"
      machine.vm.provider "virtualbox" do |v|
          v.name = name
          v.customize ["modifyvm", :id, "--memory", 200]
      end
    end
  end
end
